services:
  #Database
  ths_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: ths_db
  #Web
  ths_wp:
    depends_on:
      - ths_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8096:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: ths_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: ths_
    container_name: ths_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  ths_myadmin:
    image: phpmyadmin:latest
    container_name: ths_myadmin
    restart: "no"
    ports:
      - 5016:80
    environment:
      PMA_HOST: ths_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - ths_db
volumes:
  db_data:
  wp-content:
